{\rtf1\ansi\ansicpg949\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fswiss\fcharset0 ArialMT;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl337\partightenfactor0

\f0\fs29\fsmilli14667 \cf2 \expnd0\expndtw0\kerning0
jenkins:
\f1 \

\f0 \'a0 agentProtocols:
\f1 \

\f0 \'a0 - "JNLP4-connect"
\f1 \

\f0 \'a0 - "Ping"
\f1 \

\f0 \'a0 authorizationStrategy:
\f1 \

\f0 \'a0\'a0\'a0 loggedInUsersCanDoAnything:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 allowAnonymousRead: false
\f1 \

\f0 \'a0 clouds:
\f1 \

\f0 \'a0 - kubernetes:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 containerCap: 10
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 containerCapStr: "10"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 jenkinsTunnel: "jenkins-agent:50000"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 jenkinsUrl: "http://jenkins:80"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 maxRequestsPerHost: 32
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 maxRequestsPerHostStr: "32"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 name: "kubernetes"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 namespace: "default"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 podLabels:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 - key: "jenkins/jenkins-jenkins-slave"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 value: "true"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 serverUrl: "https://kubernetes.default"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 templates:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 - containers:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 - args: "^$\{computer.jnlpmac\} ^$\{computer.name\}"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 command: ""
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 envVars:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 - envVar:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 key: "JENKINS_URL"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 value: "http://192.168.56.11"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 image: "jenkins/inbound-agent:4.3-4"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 livenessProbe:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 failureThreshold: 0
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 initialDelaySeconds: 0
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 periodSeconds: 0
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 successThreshold: 0
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 timeoutSeconds: 0
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 name: "jnlp"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 resourceLimitCpu: "512m"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 resourceLimitMemory: "512Mi"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 resourceRequestCpu: "512m"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 resourceRequestMemory: "512Mi"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 workingDir: "/home/jenkins"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 hostNetwork: false
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 label: "jenkins-jenkins-slave "
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 name: "default"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 nodeUsageMode: NORMAL
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 podRetention: "never"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 runAsGroup: "993"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 runAsUser: "1000"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 serviceAccount: "jenkins"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 volumes:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 - hostPathVolume:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 hostPath: "/usr/bin/kubectl"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 mountPath: "/usr/bin/kubectl"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 - hostPathVolume:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 hostPath: "/bin/docker"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 mountPath: "/bin/docker"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 - hostPathVolume:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 hostPath: "/var/run/docker.sock"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0\'a0 mountPath: "/var/run/docker.sock"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0\'a0\'a0 yamlMergeStrategy: "override"
\f1 \

\f0 \'a0 crumbIssuer:
\f1 \

\f0 \'a0\'a0\'a0 standard:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 excludeClientIPFromCrumb: true
\f1 \

\f0 \'a0 disableRememberMe: false
\f1 \

\f0 \'a0 disabledAdministrativeMonitors:
\f1 \

\f0 \'a0 - "hudson.model.UpdateCenter$CoreUpdateMonitor"
\f1 \

\f0 \'a0 - "jenkins.diagnostics.RootUrlNotSetMonitor"
\f1 \

\f0 \'a0 - "jenkins.security.UpdateSiteWarningsMonitor"\'a0 
\f1 \

\f0 \'a0 labelAtoms:
\f1 \

\f0 \'a0 - name: "master"
\f1 \

\f0 \'a0 markupFormatter: "plainText"
\f1 \

\f0 \'a0 mode: NORMAL
\f1 \

\f0 \'a0 myViewsTabBar: "standard"
\f1 \

\f0 \'a0\'a0numExecutors: 0
\f1 \

\f0 \'a0 primaryView:
\f1 \

\f0 \'a0\'a0\'a0 all:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 name: "all"
\f1 \

\f0 \'a0 projectNamingStrategy: "standard"
\f1 \

\f0 \'a0 quietPeriod: 5
\f1 \

\f0 \'a0 remotingSecurity:
\f1 \

\f0 \'a0\'a0\'a0 enabled: true
\f1 \

\f0 \'a0 scmCheckoutRetryCount: 0
\f1 \

\f0 \'a0 securityRealm: "legacy"
\f1 \

\f0 \'a0 slaveAgentPort: 50000
\f1 \

\f0 \'a0 updateCenter:
\f1 \

\f0 \'a0\'a0\'a0 sites:
\f1 \

\f0 \'a0\'a0\'a0 - id: "default"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 url: "https://raw.githubusercontent.com/IaC-Source/Jenkins-updateCenter/main/update-center.json"
\f1 \

\f0 \'a0 views:
\f1 \

\f0 \'a0 - all:
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 name: "all"
\f1 \

\f0 \'a0 viewsTabBar: "standard"
\f1 \

\f0 security:
\f1 \

\f0 \'a0 apiToken:
\f1 \

\f0 \'a0\'a0\'a0 creationOfLegacyTokenEnabled: false
\f1 \

\f0 \'a0\'a0\'a0 tokenGenerationOnCreationEnabled: false
\f1 \

\f0 \'a0\'a0\'a0 usageStatisticsEnabled: true
\f1 \

\f0 \'a0 sSHD:
\f1 \

\f0 \'a0\'a0\'a0 port: -1
\f1 \

\f0 unclassified:
\f1 \

\f0 \'a0 buildDiscarders:
\f1 \

\f0 \'a0\'a0\'a0 configuredBuildDiscarders:
\f1 \

\f0 \'a0\'a0\'a0 - "jobBuildDiscarder"
\f1 \

\f0 \'a0 fingerprints:
\f1 \

\f0 \'a0\'a0\'a0 fingerprintCleanupDisabled: false
\f1 \

\f0 \'a0\'a0\'a0 storage: "file"
\f1 \

\f0 \'a0 gitSCM:
\f1 \

\f0 \'a0\'a0\'a0 createAccountBasedOnEmail: false
\f1 \

\f0 \'a0\'a0\'a0 showEntireCommitSummaryInChanges: false
\f1 \

\f0 \'a0\'a0\'a0 useExistingAccountWithSameEmail: false
\f1 \

\f0 \'a0 junitTestResultStorage:
\f1 \

\f0 \'a0\'a0\'a0 storage: "file"
\f1 \

\f0 \'a0 location:
\f1 \

\f0 \'a0\'a0\'a0 adminAddress: "address not configured yet <nobody@nowhere>"
\f1 \

\f0 \'a0 mailer:
\f1 \

\f0 \'a0\'a0\'a0 charset: "UTF-8"
\f1 \

\f0 \'a0\'a0\'a0 useSsl: false
\f1 \

\f0 \'a0\'a0\'a0 useTls: false
\f1 \

\f0 \'a0 pollSCM:
\f1 \

\f0 \'a0\'a0\'a0 pollingThreadCount: 10
\f1 \

\f0 tool:
\f1 \

\f0 \'a0 git:
\f1 \

\f0 \'a0\'a0\'a0 installations:
\f1 \

\f0 \'a0\'a0\'a0 - home: "git"
\f1 \

\f0 \'a0\'a0\'a0\'a0\'a0 name: "Default"}